server:
  port: 8085
  shutdown: graceful

logging:
  level:
    root: info

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
  application:
    name: larina-app-name
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

printer:
  service: false
